### ISSUE TITLE
Pedido de colaboração

### ISSUE THREAD

**Issue by drbeco** [drbeco/qqcoisa18#2]
Deixe uma mensagem aqui para ser adicionado.

**Comment by KewinLima** [comment]
Favor adicionar 'KewinLima'

Date: Wed, 7 Oct 2015 19:58:05 -0700

**Comment by CassiaReginaFBarbosa** [comment]
Bom dia, professor. Favor adicionar 'CassiaReginaFBarbosa'

**Comment by aronsales** [comment]
Bom dia professor, Favor adicionar "aronsales".

**Comment by wesleysilas** [comment]
Grande Ruben... me adicione, por favor!

**Comment by hgees** [comment]
Bom dia profesor, favor adicionar "hgees"

**Comment by RafaelRSPX** [comment]
Bom dia professor. Favor adicionar 'RafaelRSPX'.

**Comment by gabrielgou** [comment]
Bom dia, por favor adicionar "gabrielgou"!

**Comment by eilins** [comment]
Bom dia, Professor. Favor adicionar "eilins".

**Comment by tonyfrance** [comment]
bom dia professor, por favor adicionar "tonyfrance".

**Comment by flavioduart** [comment]
Bom dia, professor. Favor adicionar 'flavioduart'

**Comment by thiagooqueiroz** [comment]
Bom dia Professor , favor adicionar "thiagooqueiroz"

**Comment by priscilasousa** [comment]
Bom dia Professor, tudo bem? Pode me adicionar por gentileza? "priscilasousa"

**Comment by dmfds** [comment]
Bom dia professor Ruben, poderia me adicionar "dmfds". Obrigado!

**Comment by wirlany** [comment]
Boa tarde Professor! 
Peço que me adicione por favor!  
Wirlany

**Comment by drbeco** [comment]
---
Até aqui, todos adicionados;

**Comment by japds** [comment]
Boa tarde professor. Favor adicionar 'japds'

**Comment by guidoferrario** [comment]
Boa tarde professor, por favor adicionar "guidoferrario". Obrigado!

**Comment by wagner-lucas** [comment]
Boa tarde professor. por favor adicionar "wlfds"

**Comment by drbeco** [comment]
---
Até aqui adicionado.

Wagner, para adicioná-lo no github como colaborador, é preciso usar "wagner-lucas" e não "wlfds"!

**Comment by alessonrenato** [comment]
Boa noite professor. por favor adicionar "alessonrenato"

**Comment by JorgeEd13** [comment]
Boa noite professor. Por favor adicionar "JorgeEd13"

**Comment by drbeco** [comment]
---

Até aqui, adicionado.

**Comment by halanamelo** [comment]
Boa noite professor. Por favor adicionar "halanamelo". Obg

**Comment by bmhori** [comment]
Boa noite professor, por favor adiconar "bmhori". Obrigada!

**Comment by wagner-lucas** [comment]
Mil desculpas professor, foi um mal entendido, não irá acontecer novamente.

**Comment by iWarhead** [comment]
Bom dia professor, favor adicionar iWarhead.

**Comment by lucasmgila** [comment]
Bom dia professor, por favor adicionar "lucasmgila". OBG!

**Comment by pontesupe** [comment]
Boa noite prof. Ruben, por favor adicionar "pontesupe"

**Comment by felipecampelo** [comment]
Boa noite, Ruben. Por favor adicionar "felipecampelo". Obg

**Comment by matheusmoraismoura** [comment]
Boa noite professor, favor adicionar "matheusmoraismoura" . Obrigado

**Comment by drbeco** [comment]
Adicionado até aqui.

---

**Comment by danielhmacedo** [comment]
Boa noite professor, favor adicionar danielhmacedo . Obrigado.
